// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FormController from "./form_controller"
application.register("form", FormController)

import ViewTransitionIntersectionController from "./view_transition_intersection_controller"
application.register("view-transition-intersection", ViewTransitionIntersectionController)
