---
EnableDefaultLinters: true
glob: "**/*.{html}{+*,}.erb"
exclude:
  - vendor/bundle/**/*
  - node_modules/**/*
  - tmp/**/*
  - log/**/*

EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: true
